SELECT * FROM TOP30B WHERE INDUSTRY='Technology' ORDER BY INDUSTRY,AGE;

SELECT * FROM TOP30B;

SELECT b.FULL_NAME,b.COUNTRY FROM TOP30B b;

SELECT b.FULL_NAME,b.NET_WORTH_USD AS wealth FROM TOP30B b;

SELECT * FROM TOP30B
WHERE COUNTRY='USA';

SELECT b.FULL_NAME,b.NET_WORTH_USD FROM TOP30B b
WHERE NET_WORTH_USD>100;

SELECT b.FULL_NAME,b.AGE FROM TOP30B b
WHERE AGE>70;

SELECT * FROM TOP30B
WHERE COUNTRY IN ('China','India');

SELECT B.FULL_NAME,B.NET_WORTH_USD FROM TOP30B B
ORDER BY NET_WORTH_USD DESC;

SELECT B.FULL_NAME,B.NET_WORTH_USD FROM TOP30B B
ORDER BY NET_WORTH_USD DESC FETCH FIRST 5 ROWS ONLY;

SELECT B.FULL_NAME,B.AGE FROM TOP30B B
ORDER BY B.AGE DESC FETCH FIRST 5 ROWS ONLY;

SELECT B.FULL_NAME FROM TOP30B B
WHERE FULL_NAME LIKE 'M%';

SELECT * FROM TOP30B
WHERE FULL_NAME LIKE '%son%';
-- or
SELECT * FROM TOP30B
WHERE UPPER(FULL_NAME) LIKE UPPER('%SON%');

SELECT * FROM TOP30B
WHERE COUNTRY LIKE '%a';

SELECT * FROM TOP30B
WHERE NET_WORTH_USD BETWEEN 80 AND 100;

SELECT * FROM TOP30B
WHERE INDUSTRY IN ('Technology','Finance','Retail');

SELECT DISTINCT B.COUNTRY FROM TOP30B B;

SELECT DISTINCT B.INDUSTRY FROM TOP30B B;

SELECT FULL_NAME,
    CASE
    WHEN NET_WORTH_USD>150 THEN 'ULTRA-RICH'
    WHEN NET_WORTH_USD<=149 AND NET_WORTH_USD>=100 THEN 'VERY RICH'
    WHEN NET_WORTH_USD<100 THEN 'RICH'
END AS RICHNESS
FROM TOP30B;

SELECT * FROM TOP30B B
WHERE COUNTRY='USA' ORDER BY NET_WORTH_USD DESC
FETCH FIRST 3 ROWS ONLY;

SELECT B.FULL_NAME,NVL(AGE,0) AS AGE FROM TOP30B B;












