SELECT COUNT(*) FROM INVESTORS_JT;
SELECT COUNT(*) FROM INVESTMENTS_JT;

SELECT * FROM INVESTORS_JT;
SELECT * FROM INVESTMENTS_JT;

-- INNER-JOIN
SELECT ITOR.FULL_NAME,SUM(IMENT.INVESTMENT_AMOUNT)
FROM INVESTORS_JT ITOR
INNER JOIN INVESTMENTS_JT IMENT
ON ITOR.INVESTOR_ID = IMENT.INVESTOR_ID
WHERE ITOR.INVESTOR_ID=1
GROUP BY ITOR.FULL_NAME;

-- RIGHT-JOIN
SELECT * FROM INVESTORS_JT ITOR
RIGHT JOIN INVESTMENTS_JT IMENT
ON ITOR.INVESTOR_ID = IMENT.INVESTOR_ID;

-- LEFT-JOIN
SELECT * FROM INVESTORS_JT ITOR
LEFT JOIN INVESTMENTS_JT IMENT
ON ITOR.INVESTOR_ID = IMENT.INVESTOR_ID;

-- FULL-JOIN
SELECT * FROM INVESTORS_JT ITOR
FULL JOIN INVESTMENTS_JT IMENT
ON ITOR.INVESTOR_ID=IMENT.INVESTOR_ID;

-- LEFT-ANTI JOIN
SELECT *
FROM INVESTMENTS_JT IMENT
         LEFT JOIN INVESTORS_JT ITOR
                   ON IMENT.INVESTOR_ID = ITOR.INVESTOR_ID
WHERE NOT EXISTS (
    SELECT 1
    FROM INVESTORS_JT v
    WHERE v.INVESTOR_ID = IMENT.INVESTOR_ID
);







