WITH high_salary AS (
    SELECT *
    FROM UZ_EMPLOYEES
    WHERE SALARY > 10000
)
SELECT
    high_salary.EMP_NAME,
    high_salary.CITY,
    high_salary.SALARY
FROM high_salary
ORDER BY SALARY DESC ;

-- --------------------------------------

WITH TOTAL_SAL_CITY AS (
    SELECT E.CITY,
           SUM(SALARY)
    FROM UZ_EMPLOYEES E
    GROUP BY E.CITY HAVING SUM(SALARY)>30000
)
SELECT TOTAL_SAL_CITY.CITY
FROM TOTAL_SAL_CITY;


WITH DEP_AVGSAL AS(
    SELECT U.DEPARTMENT, FLOOR(AVG(U.SALARY)) AS AVERAGE
    FROM UZ_EMPLOYEES U
    GROUP BY U.DEPARTMENT
)
SELECT * FROM DEP_AVGSAL
WHERE AVERAGE>9000;



WITH CITY_EMP_VICE AS (
    SELECT
        U.CITY,
        COUNT(*) AS EMP_COUNT
    FROM UZ_EMPLOYEES U
    GROUP BY U.CITY
)
SELECT CITY,EMP_COUNT FROM CITY_EMP_VICE;


-- NESTED CTE:
WITH dept_avg AS (
    SELECT DEPARTMENT,
           FLOOR(AVG(SALARY)) AS AVG_SALARY
    FROM UZ_EMPLOYEES
    GROUP BY DEPARTMENT
),
    ABOVE_DEPT_AVG AS (
        SELECT
            U.EMP_ID,
            U.EMP_NAME,
            U.CITY,
            U.DEPARTMENT,
            U.SALARY,
            d.AVG_SALARY
        FROM UZ_EMPLOYEES U
        JOIN dept_avg D
        ON U.DEPARTMENT = d.DEPARTMENT
        WHERE U.SALARY > D.AVG_SALARY
    )
SELECT
    EMP_NAME,
    DEPARTMENT,
    SALARY,
    AVG_SALARY
FROM ABOVE_DEPT_AVG
ORDER BY DEPARTMENT,SALARY DESC ;














